project_name: statiks

builds:
  -
    main: ./main.go
    binary: statiks
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goarch: 386

release:
  github:
    owner: janiltonmaciel
    name: statiks


# Mac OS Homebrew
brews:
  -
    # Reporitory to push the tap to.
    tap:
      owner: janiltonmaciel
      name: homebrew-tap

    description: "Fast, zero-configuration, static HTTP filer server."
    homepage: "https://github.com/janiltonmaciel/statiks"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Custom install
    install: |
      bin.install "statiks"

    test: |
      assert_match version.to_s, shell_output("#{bin}/statiks --version")

dockers:
  -
    image_templates:
    - "janilton/statiks:latest"
    - "janilton/statiks:{{ .Major }}.{{ .Minor }}"

    extra_files:
      - go.mod
      - go.sum
      - README.md
      - main.go
      - cmd
      - lib

changelog:
  sort: asc
  filters:
    exclude:
    - '^Update README.md with release'
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
