[[constraint]]
  branch = "master"
  name = "github.com/janiltonmaciel/middleware"

[[constraint]]
  branch = "master"
  name = "github.com/phyber/negroni-gzip"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.4.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
